### ISSUE TITLE
Servers without domain extensions not allowed

### ISSUE THREAD

**Issue by xaviex** [maikebing/GitLab.VisualStudio#1]
When trying to attach to a server without a domain extension such as http://my-gitserv/ on the login, it will flag it as an invalid URL.

**Comment by xaviex** [comment]
Made a few modifications on my own to allow it but i seem to then be getting 401 errors.

**Comment by maikebing** [comment]
[GitLab.VisualStudio.zip](https://github.com/maikebing/GitLab.VisualStudio/files/973716/GitLab.VisualStudio.zip)

**Comment by xaviex** [comment]
Seem to Work so far!
