### ISSUE TITLE
Default storage folder

### ISSUE THREAD

**Issue by dedisoft** [maikebing/GitLab.VisualStudio#13]
Hi,

Modify default repo folder on Visual Studio.

Then try to duplicate or create new repo, default folder is always c:\users\mylogin\Source\...

New folder never used.

Regards,

**Comment by maikebing** [comment]
What you version  ?
look here  please  #3

**Comment by dedisoft** [comment]
Latest version of VS and plugin too.

I've reinstalled my computer. I will try again and let you informed

**Comment by maikebing** [comment]
not need reinstall!
try new version of plugin  !

**Comment by maikebing** [comment]
Default storage folder is not save to plugin's config file!
so . you are right !
I'ill fix it !

**Comment by dedisoft** [comment]
Hi,

I've reinstalled due to hard disk failure, not because of this tool !

So now I can use another storage path , but I need to choose it each time. Perhaps because not saved on confid file, like you wrote.

Thanks for your support
