### ISSUE TITLE
The remove server return an error (BadRequest)

### ISSUE THREAD

**Issue by tokm** [maikebing/GitLab.VisualStudio#15]
I'm using the gitlab addin version 1.0.0.112 for Visual Studio 2017.  When I try to publish to GitLab I get error 'The remote server returned an error (BadRequest)'  On old projects that I have previously published to gitlab I can sync those without any problems.  Only on a new project, publishing for the first time I get this error.  Any ideas?

**Comment by maikebing** [comment]
#14
