### ISSUE TITLE
GitLab and LDAP credentials

### ISSUE THREAD

**Issue by BlackGad** [maikebing/GitLab.VisualStudio#17]
GitLab does not login with LDAP credentials. Is there any chance to support this feature?

**Comment by maikebing** [comment]
I do not have an LDAP server that I can use for testing

**Comment by BlackGad** [comment]
Have you some extended logging? Because it is just login failed popup dialog with out any additional information for now.

**Comment by dominicdejacomo** [comment]
If you create a personal access token (https://yourgitlaburl.com/profile/personal_access_tokens) and select 2fa and use your ldap username + your PAT you will be able to login and use the plug-in.

**Comment by IanKemp** [comment]
It would be useful to add the workaround provided by @dominicdejacomo for people using LDAP, to the main page.

**Comment by Tuumke** [comment]
Work arround is not working for me :( 
![afbeelding](https://user-images.githubusercontent.com/935617/53474431-5ac1b000-3a6d-11e9-8659-687601dd8adb.png)

**Comment by maikebing** [comment]
Can you give me a test account? @Tuumke

**Comment by Tuumke** [comment]
> 
> 
> Can you give me a test account? @Tuumke

No sorry, it has no external access :(
