### ISSUE TITLE
Cannot login through VS integration

### ISSUE THREAD

**Issue by paulhiggs** [maikebing/GitLab.VisualStudio#22]
I can login to the GitLab web portal, create a repository and clone it in Visual Studio, but when I try to publish back to GitLab, I get a "401 Unauthorized". Tried all 4 authentication methods, never asked for a token.

I am using 1.0.0.122 of the GitLab extension.

![image](https://user-images.githubusercontent.com/3158807/37864561-482bc070-2f47-11e8-869e-10fb003d5d21.png)

**Comment by paulhiggs** [comment]
Solved this myself. The "Connect to Gitlab" dialog wants the Token generated in Gitlab, not the account password.

**Comment by Hbn71** [comment]
which token ?! how to get it?!

**Comment by Hbn71** [comment]
> Solved this myself. The "Connect to Gitlab" dialog wants the Token generated in Gitlab, not the account password.

which token ?! how to get it?!

**Comment by manishdimensionsoftware** [comment]
@Hbn71 [Personal Access Tokens](https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html).

I have this same problem and entering a personal access token didn't fix it...

BTW anyone notice the irony of a Gitlab extension hosted on Github? 😆

**Comment by gauravupadhyay28** [comment]
@paulhiggs - your suggestion (Personal Access Tokens) worked for me . Thank you very much.
