### ISSUE TITLE
can't install update 2.5.2.2566

### ISSUE THREAD

**Issue by TFreudi1** [maikebing/GitLab.VisualStudio#24]
I have Win10 1709 (16299) I can't install the gitlab update. I get a lot of similiars errors like:
22.05.2018 09:30:52 - Skipping non-applicable package Microsoft.Windows.UniversalCRT.Msu.8: Die aktuelle Betriebssystemversion 10.0.16299.0 liegt nicht im unterstützten Versionsbereich "[6.2,6.3)".
22.05.2018 09:30:52 - Skipping non-applicable package Microsoft.Windows.UniversalCRT.Msu.81: Die aktuelle Betriebssystemversion 10.0.16299.0 liegt nicht im unterstützten Versionsbereich "[6.3,6.4)".
22.05.2018 09:30:52 - Skipping non-applicable package Microsoft.Windows.D3DCompiler.Msu.Win7: Die aktuelle Betriebssystemversion 10.0.16299.0 liegt nicht im unterstützten Versionsbereich "[6.1,6.2)".
liegt nicht im unterstützten Versionsbereich->Version is not supported

**Comment by maikebing** [comment]
?????

**Comment by TFreudi1** [comment]
Yes thats strange, I got the messsage that an update for the Gitlab Extension is avaible but your Version number is starting with 1 and this was 2.5.2.2566, and it only happens in the VS Installation in my office, not here at home. I you have no idea I will close it. I have only a few extensions installed and non GitHub/gitlab related, and I'm quite shure that your symbol (a fox?) was in the update message. Tomorrow I can send you the whole log-file if you are interested in.
