### ISSUE TITLE
Could not resolve proxy: none

### ISSUE THREAD

**Issue by DonPetry-EY** [maikebing/GitLab.VisualStudio#26]
Win10. I received the following error attempting to use this Extension while on CorpNet behind a Proxy:

"Git failed with a fatal error.
unable to access 'https://gitlab.com/myproject': Could not resolve proxy: none"

I searched but couldn't find any documentation or setting for Proxy.  It doesn't seem to be reading from the browser settings.

**Comment by maikebing** [comment]
Just like you said! Next version I will support proxy.

**Comment by maikebing** [comment]
@DonPetry-EY   read this  https://stackoverflow.com/search?q=git+proxy
