### ISSUE TITLE
Error when login

### ISSUE THREAD

**Issue by loretguib** [maikebing/GitLab.VisualStudio#29]
I have this error when I tried to connect:
"Failed to login
Unexpected character encountered while parsing value: <. Path '', line 0, position 0."

I write all the required fields ok. 
This is the latest version installed from VS extensions menu.

Please help, I need to connect to gitlab. Thank you!!

**Comment by maikebing** [comment]
Can you test this?
http://vsixgallery.com/extension/54803a44-49e0-4935-bba4-7d7d91682273/

**Comment by didix21** [comment]
I have the same error. I have installed the last version. There is any solution for that ? 
![error_gitlab](https://user-images.githubusercontent.com/12051781/44521392-2e4e6500-a6d3-11e8-8943-6367a17b1f64.PNG)

**Comment by maikebing** [comment]
try new version !

**Comment by ChaozProgramming** [comment]
Hi,

I'm running a gitlab server on my synology. I can access it succesfully but when i try to connect with visual studio I'm getting this error. Any idea what could be wrong?

![afbeelding](https://user-images.githubusercontent.com/28703878/71562862-ceb25780-2a86-11ea-9a9c-f5fce7bc0351.png)
