### ISSUE TITLE
login failed:404 Not Found

### ISSUE THREAD

**Issue by ken-io** [maikebing/GitLab.VisualStudio#31]
GitLab Server：https://gitlab.com/
Auth Type：GitLab ApiV4

**Comment by maikebing** [comment]
I tried, but it seemed right, if your username and password were okay.

**Comment by ken-io** [comment]
if my username or password  is wrong,it will response 401,not 404

**Comment by ElektroKill** [comment]
I have the same issue

**Comment by ffes** [comment]
Same for me, on gitlab,com as well as on our on-premise GitLab CE

**Comment by shadow-cs** [comment]
Same here

**Comment by fredsongco** [comment]
> > Same for me, on gitlab,com as well as on our on-premise GitLab CE
> 
> Same here

Encountering the same issue

**Comment by peterjmorgan** [comment]
Same issue

**Comment by AxleUnix** [comment]
+1, same situation

**Comment by EduardoSanchez030** [comment]
same here

**Comment by Eweol** [comment]
same here

**Comment by IcySon55** [comment]
Same issue here

**Comment by Coriolanuss** [comment]
Encountered the same issue. Checking the "Two Factor..." checkbox **helped** me for some reason, though no additional authentication was prompted.
![image](https://user-images.githubusercontent.com/6977530/48416741-a5871880-e759-11e8-9871-c409ca051ece.png)

**Comment by ffes** [comment]
> Checking the "Two Factor..." checkbox helped me for some reason, though no additional authentication was prompted.

@Coriolanuss Great find!

I think this is why. When you look at https://gitlab.com/profile/personal_access_tokens you will see:

> **Personal Access Tokens**
>
> You can generate a personal access token for each application you use that needs access to the GitLab API.
>
>You can also use personal access tokens to authenticate against Git over HTTP. They are the only accepted password when you have Two-Factor Authentication (2FA) enabled.

Not sure why it doesn't require me to have 2FA enabled on my account when using a token, but still using the checkbox helps. And indeed no additional authentication was prompted.

**Comment by maikebing** [comment]
```
V1.0.160

Automatically detects the API version of Gitlab
```
