### ISSUE TITLE
能不能在团队资源管理器里面增加一个打开当前文件的功能

### ISSUE THREAD

**Issue by chrsas** [maikebing/GitLab.VisualStudio#33]
目前的在VS里进行历史记录比较后的差异项，在团队资源管理器里呈现后，右键文件打开时，打开的是提交记录里的文件，没法打开当前项目里对应的实际文件，颇为不变，希望能加上一个打开当前文件的功能。

**Comment by maikebing** [comment]
我也遇到这样一个恶心问题。

**Comment by maikebing** [comment]
vs中好像有这个功能。
