### ISSUE TITLE
Gitlab 提交没法追踪到当前分支

### ISSUE THREAD

**Issue by chrsas** [maikebing/GitLab.VisualStudio#35]
我在代码上，右键 -> Gitlab -> 提交，打开的URL一直都是 master 分支，但是当前的默认分支为develop，导致需要一直手动改Url

![image](https://user-images.githubusercontent.com/6327955/49004532-69af7280-f19f-11e8-8e10-45fa8de42e24.png)

生成的URL
```
https://gitlab.XXXX.net/xxx/xxx/xxx/commits/master/src/xxx/xxx/xxxx.cs#L16
```

**Comment by maikebing** [comment]
谢谢， 下个版本修复一下

**Comment by maikebing** [comment]
已经修复
