### ISSUE TITLE
Cannot Login from VS 2017

### ISSUE THREAD

**Issue by ani-sm** [maikebing/GitLab.VisualStudio#37]
Can't login with Team Explorer->Connect, because extension try loading "NewtonSoft.JSON 11.0.0.0", what's very old, and failed.
The Installation (%AppData%\Microsoft\VisualStudio\15xxx\Extensions\somethingcryptic\) comes with Version 12.0.1.22727.
 Error with latest release of the extension.

**Comment by maikebing** [comment]
#36

**Comment by maikebing** [comment]
@ani-sm   https://ci.appveyor.com/project/MaiKeBing/gitlab-visualstudio/branch/master/artifacts
