### ISSUE TITLE
Unable use server IP with other PORT

### ISSUE THREAD

**Issue by DanielS4n** [maikebing/GitLab.VisualStudio#4]
I have GitLab server but the VS extension report random errors, after project creation on my server:
http://79.8.134.146:10080
The client extension create the project in the server but immediatly after report strange connection error to invalid local server:
http://localhost:10080/..
se attached image.
Same problem when I try to clone, the client extension show me the correct project (previous created) but when confirm unable to clone because return the same error (of creation)

I think was little problem on the code when reconnect to server replacing the IP with localhost

I wait for patch!! .. thanks in advance!!

**Comment by luky92** [comment]
@DanielS4n no image provided

**Comment by maikebing** [comment]
This is a configuration problem.
You can edit gitlab.rb
and modify external_url  !

> 
> ## Url on which GitLab will be reachable.
> ## For more details on configuring external_url see:
> ## https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/doc/settings/configuration.md#configuring-the-external-url-for-gitlab
> external_url 'https://git.xjsf.org' # default: http://hostname

**Comment by maikebing** [comment]
The reason is that after we log in, we used the GitLab to return the server address instead of the address you entered.
