### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by ffes** [maikebing/GitLab.VisualStudio#47]
### Installed product versions
- Visual Studio: 2017 v15.9.10 Professional and v15.9.9 Community Edition
- This extension: Git commit 5c6b62b1107d98ff87ce3de598d0ab1627aea948

### Description
I am not able to build the current master.  
I want to find out why the extension doesn't work with the GitLab CE in our LAN.

### Steps to recreate
1. Clone the repository from GitHub
2. Open in Visual Studio 2017.9.10
3. Run `Build Solution`.

### Current behavior
I get this error building `GitLab.VisualStudio.csproj` (other projects within the solution build fine):

```
1>------ Build started: Project: GitLab.VisualStudio, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3274: The primary reference "C:\Source\GitLab.VisualStudio\build\Debug\GitLab.TeamFoundation.16.dll" could not be resolved because it was built against the ".NETFramework,Version=v4.7.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.6.1".
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3277: Found conflicts between different versions of "Microsoft.TeamFoundation.Git.Controls" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3277: Found conflicts between different versions of "Microsoft.VisualStudio.ComponentModelHost" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
1>  GitLab.VisualStudio -> C:\Source\GitLab.VisualStudio\build\Debug\GitLab.VisualStudio.dll
1>C:\Source\GitLab.VisualStudio\packages\Microsoft.VSSDK.BuildTools.15.1.192\tools\VSSDK\Microsoft.VsSDK.targets(578,5): error MSB4057: The target "GenerateFileManifest" does not exist in the project.
========== Build: 0 succeeded, 1 failed, 5 up-to-date, 0 skipped ==========
```

### Expected behavior
It builds without an error

### Tried to solve this by
* Upgrade all the nuget packages. This fails because some most projects are still targeted to v4.6.1
* Retarget all the projects to v4.7.2. This fails because `GitLab.VisualStudio.csproj` becomes incompatible.

**Comment by maikebing** [comment]
Try the new version, it should be OK

**Comment by ffes** [comment]
As I mentioned in my original post, I am using the latest version (at the moment of writing): commit 5c6b62b1107d98ff87ce3de598d0ab1627aea948 of 2019-03-17 17:01 +0800

**Comment by Rennerdo30** [comment]
Had the same problem. 
Check your Visual Studio installation and verify, that you have the correct .NET Development Tools installed
