### ISSUE TITLE
Not able to set up GitLab in VisualStudio

### ISSUE THREAD

**Issue by PSJayKay** [maikebing/GitLab.VisualStudio#49]
### Installed product versions
- Visual Studio: 2017 Enterprise edtion
- This extension: [example 1.1.21]

### Description
I just download gitlab flow for VS 2017. I am trying to gitlab from git hub.

It does not look like I have an option to log in?

### Steps to recreate
1. installed the plug in 
2. opened a project that I moved and branched within gitlab using github desktop app. 
3.opened the project and getting this screenshot
![2019-04-13 15_10_10-Grades - Microsoft Visual Studio](https://user-images.githubusercontent.com/32443244/56084832-df3e7700-5dfe-11e9-9ebe-866658f1af86.png)
. 

### Current behavior
no option to log in or anything 

### Expected behavior
Explain what it should be doing after it's fixed.

**Comment by maikebing** [comment]
You open a solution and try it.

**Comment by PSJayKay** [comment]
I now this. I have given up on this for now. I will loop back around if /when I am ready to try gitlab again.
