### ISSUE TITLE
cannot connect to custom gitlab server with different port

### ISSUE THREAD

**Issue by ytianxia6** [maikebing/GitLab.VisualStudio#50]
### Installed product versions
- Visual Studio: Visual Studio 2019 Enterprise Preview
- This extension: 1.0.182

### Description
I can not connect to my gitlab server.
our https port is 7443 and ssh port is 7022.

### Steps to recreate
1. install the plugin
![image](https://user-images.githubusercontent.com/20197887/56256010-9980f780-60f9-11e9-9140-411a798ade19.png)

2. Connect to GitLab
![image](https://user-images.githubusercontent.com/20197887/56256040-abfb3100-60f9-11e9-9125-3cc1d9fae55f.png)
![image](https://user-images.githubusercontent.com/20197887/56256078-cc2af000-60f9-11e9-9063-3abf4471c3c7.png)

then I got the error:
![image](https://user-images.githubusercontent.com/20197887/56256110-e795fb00-60f9-11e9-9ac1-981d2cef2dd3.png)

3. when use email to login:
![image](https://user-images.githubusercontent.com/20197887/56256145-05636000-60fa-11e9-95b8-40710f757eb4.png)

I got the error:
![image](https://user-images.githubusercontent.com/20197887/56256157-10b68b80-60fa-11e9-9178-0f5c8fdd7670.png)

### Expected behavior
how can i connect?

**Comment by maikebing** [comment]
Can I give you a test address and a user?

**Comment by ytianxia6** [comment]
give me? I test on your server?  Ok, you can send to me by mail or message.

**Comment by ytianxia6** [comment]
I'm trying to  clone the  source code and debug it.
now i found it throw a exception in the GitLab.VisualStudio.Services.WebService.LoadProjects(), line 38, after some foreach.

I attemp to list the projects.

**Comment by ytianxia6** [comment]
![image](https://user-images.githubusercontent.com/20197887/56648175-67513600-66b5-11e9-9dd7-4e509bd0edd5.png)
it throw a System.Net.WebException after about 20 times
![image](https://user-images.githubusercontent.com/20197887/56648407-daf34300-66b5-11e9-971d-8d17ec4260ad.png)
![image](https://user-images.githubusercontent.com/20197887/56648491-083ff100-66b6-11e9-88a3-2dd4e56dabc8.png)

Is it because my project is too much?

**Comment by maikebing** [comment]
> give me? I test on your server? Ok, you can send to me by mail or message.

我写错了 。 如果你有测试账号， 可以给我一个， 我测试一下。

**Comment by ytianxia6** [comment]
> > give me? I test on your server? Ok, you can send to me by mail or message.
> 
> 我写错了 。 如果你有测试账号， 可以给我一个， 我测试一下。

呃，我编英语编的好累。。我发现其实连接是成功的，就是 LoadProjects 时，第21个异常。

**Comment by ytianxia6** [comment]
> > > give me? I test on your server? Ok, you can send to me by mail or message.
> > 
> > 
> > 我写错了 。 如果你有测试账号， 可以给我一个， 我测试一下。
> 
> 呃，我编英语编的好累。。我发现其实连接是成功的，就是 LoadProjects 时，第21个异常。

问题我已经找到了，但是不知道怎么修复 
我在浏览器输入 https://my-server:7443/api/v4/projects/?membership=true，然后F12 调试查看 header， 

```
link: <https://my-server/api/v4/projects?membership=true&order_by=created_at&owned=false&page=2&per_page=20&simple=false&sort=desc&starred=false&statistics=false&with_custom_attributes=false&with_issues_enabled=false&with_merge_requests_enabled=false>; rel="next", <https://appdev.zwcad.org.cn/api/v4/projects?membership=true&order_by=created_at&owned=false&page=1&per_page=20&simple=false&sort=desc&starred=false&statistics=false&with_custom_attributes=false&with_issues_enabled=false&with_merge_requests_enabled=false>; rel="first", <https://appdev.zwcad.org.cn/api/v4/projects?membership=true&order_by=created_at&owned=false&page=8&per_page=20&simple=false&sort=desc&starred=false&statistics=false&with_custom_attributes=false&with_issues_enabled=false&with_merge_requests_enabled=false>; rel="last"
```
在header中丢失了端口。

**Comment by ytianxia6** [comment]
> > > > give me? I test on your server? Ok, you can send to me by mail or message.
> > > 
> > > 
> > > 我写错了 。 如果你有测试账号， 可以给我一个， 我测试一下。
> > 
> > 
> > 呃，我编英语编的好累。。我发现其实连接是成功的，就是 LoadProjects 时，第21个异常。
> 
> 问题我已经找到了，但是不知道怎么修复
> 我在浏览器输入 [https://my-server:7443/api/v4/projects/?membership=true，然后F12](https://my-server:7443/api/v4/projects/?membership=true%EF%BC%8C%E7%84%B6%E5%90%8EF12) 调试查看 header，
> 
> ```
> link: <https://my-server/api/v4/projects?membership=true&order_by=created_at&owned=false&page=2&per_page=20&simple=false&sort=desc&starred=false&statistics=false&with_custom_attributes=false&with_issues_enabled=false&with_merge_requests_enabled=false>; rel="next", <https://appdev.zwcad.org.cn/api/v4/projects?membership=true&order_by=created_at&owned=false&page=1&per_page=20&simple=false&sort=desc&starred=false&statistics=false&with_custom_attributes=false&with_issues_enabled=false&with_merge_requests_enabled=false>; rel="first", <https://appdev.zwcad.org.cn/api/v4/projects?membership=true&order_by=created_at&owned=false&page=8&per_page=20&simple=false&sort=desc&starred=false&statistics=false&with_custom_attributes=false&with_issues_enabled=false&with_merge_requests_enabled=false>; rel="last"
> ```
> 在header中丢失了端口。

我检查过 gitlab 的 external_url 是正确的。

**Comment by ytianxia6** [comment]
实在找不到解决方案，无奈之下，我修改了 NGitLabPlus 库，NGitLab.Impl.HttpRequestor.Enumerable<T>.Enumerator 类，
``` csharp
                private int port;

                public Enumerator(string apiToken, Uri startUrl, ApiVersion _ApiVersion)
                {
                    this.apiToken = apiToken;
                    nextUrlToLoad = startUrl;
                    _apiVersion = _ApiVersion;

                    port = nextUrlToLoad.Port;
                }
                public bool MoveNext()
                {
                    if (buffer.Count == 0)
                    {
                        if (nextUrlToLoad == null)
                            return false;


                        if (nextUrlToLoad.Port != port)  // 修正端口
                        {
                            var ub = new UriBuilder(nextUrlToLoad);
                            ub.Port = port;
                            nextUrlToLoad = ub.Uri;
                        }


````

希望能有其它解决方案。

**Comment by maikebing** [comment]
修改之后解决了吗？

**Comment by ytianxia6** [comment]
是的，这样修改替换后我可以使用了。
不方便的是这样每次安装我都得手动再替换个文件。。。。

**Comment by maikebing** [comment]
NGitLabPlus 我已经提交修改 ，我弄完后发布个版本。 你测试一下，如果没问题就发新版

**Comment by maikebing** [comment]
http://vsixgallery.com/extension/54803a44-49e0-4935-bba4-7d7d91682273/  
 @ytianxia6    下载这个  测试一下看有没有问题。

**Comment by ytianxia6** [comment]
> http://vsixgallery.com/extension/54803a44-49e0-4935-bba4-7d7d91682273/
> @ytianxia6 下载这个 测试一下看有没有问题。

已经测试，没有问题。
另外建议加个 ESC 关闭窗口的功能，克隆、创建时，如果要取消，还要点击关闭按钮。
