### ISSUE TITLE
Cloning ERROR - Git failed with fatal error. Repository not found

### ISSUE THREAD

**Issue by LeadMagnet** [maikebing/GitLab.VisualStudio#51]
### Installed product versions
- Visual Studio: 2019 Professional
- This extension: 1.0.182

### Description
Cloning any GitLab repo generates the folowing error.

Git failed with fatal error. Repository {path} not found

### Steps to recreate
Assume GitLabs VS extension is installed.
1. Open VS and click View>>Team Explorer
2. Click GitLab>>Clone
3. when the clone dialog appears, select any repo, leave the install path default, click "Clone"
4. VS "Output" windows displays the following...

Cloning into 'C:\Source'...
Remote: The project you were looking for could not be found.
Error encountered while cloning the remote repository: Git failed with a fatal error.
repository 'https://gitlab.com/{user}/myrepo.git/' not found

### Current behavior
The behaviour does not happen in VS2017 for the same repos

### Expected behavior
It should clone the repo for normal usage

I have noticed in the error message the the repo path always has a trailing forward slash when there shouldn't be one. Not sure if this is the problem. 

For example, the path displayed appears as so: "https://gitlab.com/{user}/myrepo.git/"

If you cut-n-past this path into a browser you get a 404 error. Removing the trailing slash and the page displays (in any browser).

- I have tried un/re install of GIT both in the VS installer and manually.
- Tried using different "Path" parameter, same effect
- tried fresh VM with VS2019 installed, same effect
- fresh VM (W10E) with VS2017, GitLabs ext runs fine. Same repo using same target path, clones just fine.

**Comment by maikebing** [comment]
I haven't been able to reproduce the problem.Can you debug it?

**Comment by LeadMagnet** [comment]
I have no idea how to do that. None of the VS debug tools are enable when attempting to clone a repo. No solution is loaded.

No clue if it's related, using the built in Git (either command line or UI start option) generates the same error.
