### ISSUE TITLE
Why can't I clone project?

### ISSUE THREAD

**Issue by pnrbehnam** [maikebing/GitLab.VisualStudio#57]
### Installed product versions
- Visual Studio: [2019 Professional]
- This extension: [Version | 1.0.189]

### Description
I want to connect to the local gitlab server I sing in without any problem, but I can't see any branch, and of course, I couldn't clone my project and button clone is gray.

![Capture22](https://user-images.githubusercontent.com/50314306/57208888-5674be80-6feb-11e9-97b5-dd9743a293ad.PNG)

**Comment by maikebing** [comment]
Looks like a BUG, the first item can't be Clone
