### ISSUE TITLE
Re-login to GitLab (On-Premise) after password change

### ISSUE THREAD

**Issue by Tuumke** [maikebing/GitLab.VisualStudio#59]
### Installed product versions
- Visual Studio: Professional 2019 (16.1.2)
- This extension: 1.0.189

### Description
So i changed my password from my LDAP account. Now i get:
Remote: HTTP Basic: Access denied

### Current behavior
Trying to do a sync with my project.
But i now get:
Remote: HTTP Basic: Access denied
Git failed with a fatal error.
Authentication failed for 'http://gitlab/user/project.git/'

### Expected behavior
Ask me for my new password?

**Comment by Tuumke** [comment]
When trying to "quit" gitlab now, i get "The underlying connection was closed: An unexpected error occurred on a send". When i click Clone, its all empty. When i click Create, i see that it's connected to gitlab.com

**Comment by Tuumke** [comment]
Pfff.. found it..
Configuration screen > Credential Manager :( i feel sad for not thinking of this..

**Comment by danfoxley** [comment]
Change "Credential manager" in Windows Control Panel fixed this same issue for us.  I'm not sure where "Configuration Screen > Credential Manager" is. Thanks for the hint @Tuumke
