### ISSUE TITLE
關於登入的問題

### ISSUE THREAD

**Issue by auxo86** [maikebing/GitLab.VisualStudio#6]
作者你好：
我嘗試著用docker自己架了gitlab server
但是我輸入帳號密碼時總是出現錯誤@@(如附圖)
但是如果我使用git client是確定可以正常使用的。
請問是不是我哪裡沒有設定正確呢？
![image](https://cloud.githubusercontent.com/assets/13933042/25984204/e567d9ac-371b-11e7-801e-dbc04fb0ca0b.png)
另外，請問是否有支援ssh key登入呢？
非常感謝^^

**Comment by maikebing** [comment]
http 开头。 要加这个。

**Comment by auxo86** [comment]
後來發現，透過URL設定好，不要使用gitlab 的登入介面直接使用publish 的按鈕就可以成功push

不過好像沒有找到哪裡可以匯入public key...orz

**Comment by maikebing** [comment]
两步认证？
直接 在密码框中输入  key ， 然后选中下面的两步认证就可以

**Comment by maikebing** [comment]
ssh key 暂时不支持。  好像VS自己本身就不支持。 所以， 我也不好支持， 目前来说
