### ISSUE TITLE
Unable to clone Repository from self hosted instance

### ISSUE THREAD

**Issue by JRenseler** [maikebing/GitLab.VisualStudio#61]
### Installed product versions
- Visual Studio: 2019 (16.2.3)
- This extension: 1.0.189

### Description
When I try to clone a project, hosted our company instance of GitLab, I get the following error: 

> Git failed with a fatal error.
> unable to access 'https://gitlab.qitsloc.ratq.local/qs_pub/toitrack.git/': SSL certificate problem: unable to get local issuer certificate

### Steps to recreate
1. Connect to GitLab using company server address and credentials (auto)
2. Select Clone Project in Team Explorer
3. Select project to clone in upcoming dialog

### Current behavior
Exception "Git failed with a fatal error occures

### Expected behavior
No exception should occure and project should be successfully cloned

**Comment by PhilLab** [comment]
@maikebing Also experiencing this problem, is there a way of registering self-signed certificates to be accepted by the plugin?

**Comment by maikebing** [comment]
Should be a self-signed certificate that is not trusted by the operating system and the server
