### ISSUE TITLE
Login doesn't work on VS2019 / On-Premises Gitlab

### ISSUE THREAD

**Issue by ErMaqui** [maikebing/GitLab.VisualStudio#62]
### Installed product versions
- Visual Studio: 2019 Enterprise 16.3.7
- This extension: 1.0.189
- Gitlab: 12.2.9

### Description
Trying to login on gitlab doesn't work.

It isn't a password problem, because, if I enter my password incorrectly message changes.
Also, login method selection doesn't work. It always try to login with all methods:

### Screenshots

Login with correct email and password (tested on web interface):
![image](https://user-images.githubusercontent.com/8928758/69722454-726eb780-1117-11ea-8f79-de3275faa96c.png)

Login with incorrect password:
![image](https://user-images.githubusercontent.com/8928758/69722496-97fbc100-1117-11ea-88e1-7c7c2f2d32cb.png)

Thanks,

**Comment by alpercicek** [comment]
Hi,

Login input is not found.

Detail:
Microsoft Visual Studio Community 2019 - Version 16.4.0

![image](https://user-images.githubusercontent.com/20698406/70359545-36f98900-188d-11ea-8b7f-677181dac04a.png)


![image](https://user-images.githubusercontent.com/20698406/70359220-6f4c9780-188c-11ea-8055-d2afbb3882a5.png)

**Comment by OnlyHardOfficial** [comment]
Here the same problem! 
"Failed to login"
![image](https://user-images.githubusercontent.com/19652056/70382483-dafa3780-1954-11ea-9b2a-b8f86a2160c2.png)

**Comment by megant** [comment]
.

**Comment by megant** [comment]
Same here (the problem occured first !!!3 years!!! ago)
Windows 10, 
VS2019 v16.4.3, 
GitLab Extension v1.0.189. 

Guys, seriously? :)

**Comment by maikebing** [comment]
First make sure the URL, and then make sure that the GitLab version is up-to-date.

**Comment by Nowohier** [comment]
I still have this issue in 2021:

- Visual Studio 2019 Professional v 16.8.4
- User/PW is correct
- Extension is up to date (v1.0.319)
- Windows 10 Enterprise

Same issue as post above from @OnlyHardOfficial 

Anything I can do about it?
