### ISSUE TITLE
unexpected character

### ISSUE THREAD

**Issue by ChaozProgramming** [maikebing/GitLab.VisualStudio#63]
Hi,

I'm running a gitlab server on my synology. I can access it succesfully but when i try to connect with visual studio I'm getting this error. Any idea what could be wrong?

![afbeelding](https://user-images.githubusercontent.com/28703878/71562891-62842380-2a87-11ea-9053-b4a9544b829b.png)

![afbeelding](https://user-images.githubusercontent.com/28703878/71562900-87789680-2a87-11ea-95e2-fa9ef38d0921.png)

**Comment by ChaozProgramming** [comment]
I still cant login but was able to publish my project by first adding a local repository and then using the publish to remote repository function. When added my .git link from gitlab the sync was done succesfully

![afbeelding](https://user-images.githubusercontent.com/28703878/71563447-f2c66680-2a8f-11ea-9d43-37e0a7b3d932.png)

**Comment by Hfanes** [comment]
i have same issue, any solution?

**Comment by maikebing** [comment]
First make sure the URL, and then make sure that the GitLab version is up-to-date.
