### ISSUE TITLE
Can't find GitLab in connection in VS2019 team explorer after upgrade VS2019 to 16.4.2

### ISSUE THREAD

**Issue by YYG1975** [maikebing/GitLab.VisualStudio#64]
### Installed product versions
- Visual Studio: Microsoft Visual Studio Professional 2019 Version 16.4.2
- This extension: GitLab 1.0.189

### Description
Can't find GitLab section VS2019 Team Explorer Connect tab after upgrade VS2019 to 16.4.2 and GitLab extention to 1.0.189

### Current behavior
Can't find GitLab section in Team Explorer.

### Expected behavior
Can create GitLab connection in Team Explorer Connection tab.

**Comment by YYG1975** [comment]
![image](https://user-images.githubusercontent.com/59351292/71574378-6f565500-2b23-11ea-8068-e6d973adee1c.png)
Previously the connection tab has GitLab section. Now can't find it.

Below is my VS2019 version and GitLab extention version.
![image](https://user-images.githubusercontent.com/59351292/71574425-9c0a6c80-2b23-11ea-82a8-d1b9dcf0c2ce.png)

![image](https://user-images.githubusercontent.com/59351292/71574453-b6444a80-2b23-11ea-8f26-4e1f8a3865f9.png)

**Comment by rafaelf82** [comment]
Same issue here, nothing shows up about this anywhere on team explorer.

I also tried with the newest version (Version: 1.0.193 Updated: Nov 15. 2019 23:48) from http://vsixgallery.com/extension/54803a44-49e0-4935-bba4-7d7d91682273/

**Comment by jira-zz** [comment]
I have the same problem.

**Comment by hyuanvt** [comment]
Same problem.  Please fix!  Or this extension is essentially useless.

**Comment by ljubomirk** [comment]
Same problem on VS Professional 2019
Version 16.6.1

**Comment by maikebing** [comment]
The new version has been updated
