### ISSUE TITLE
So far it's working very well with Visual Studio 2015 using our company GitLab server. 

### ISSUE THREAD

**Issue by maikebing** [maikebing/GitLab.VisualStudio#7]
So far it's working very well with Visual Studio 2015 using our company GitLab server. 

With VS 2017, weirdly, I am getting fatal: unable to access 'https://gitlab.mycompany.com/myname/test2.git/': SSL certificate problem: unable to get local issuer certificate.

**Comment by loopless** [comment]
Regarding getting a test account. Sadly our company gitlab server is on a private WAN that cannot be exposed to outside users. I double checked again and Studio 2017 behaves differently to 2015. VS 2015 performs flawlessly, while 2017 shows the SSL certificate error, even though it will still , for example, allow the initial commit to GitLab.

**Comment by maikebing** [comment]
thanks
