### ISSUE TITLE
it still wont let me log into gitlab after the update, tried email & username to https://gitlab.com and check 2 factor authentication, always comes back with "Failed to login"

### ISSUE THREAD

**Issue by maikebing** [maikebing/GitLab.VisualStudio#8]
it still wont let me log into gitlab after the update, tried email & username to https://gitlab.com and check 2 factor authentication, always comes back with "Failed to login"
been having to manually sync via git cmd

**Comment by michaelcode** [comment]
I'm experiencing the same problem. How did you resolve?

**Comment by armandombi** [comment]
@michaelcode this was resolved for me on the latest update, where you can choose the the Api version you want to use to connect to gitlab, in my case v4 was the problem so using v3 works fine. Hope this helps

**Comment by michaelcode** [comment]
i choose v4 and v3 and nothing works :(
i'm assuming the login is the account we use to login the website..

**Comment by michaelcode** [comment]
i am able to use the login when i clone a project.
but the main login, i not able to use it...

**Comment by kstanowskifp** [comment]
I got the same problem. Tried login on VS2015 and VS2017, always appears message "Failed to login"

**Comment by maikebing** [comment]
#20

**Comment by michaelcode** [comment]
Worked! Thx
